theme: jekyll-theme-minimal
logo: https://www.thoughtco.com/thmb/mzclzuDpIOXx3AXm3N46hdB6GEs=/1125x1125/smart/filters:no_upscale()/3-D_DNA-56a09ae45f9b58eba4b20266.jpg
title: Thao Bioinformatics Class (BIMM143, Fall 2021)
